Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,6 +20,11 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      - name: Debug SSH Host
+        run: echo "SSH host is ${{ secrets.SSH_HOST }}"
+      - name: Test SSH connectivity
+        run: |
+            ping -c 2 ${{ secrets.SSH_HOST }} || echo "Ping failed"
 
       - name: Add SSH Key to known_hosts
         run: |
